USE VentasTech;
GO
CREATE TABLE Categorias (
 CategoriaID INT IDENTITY(1,1) PRIMARY KEY,
 Nombre VARCHAR(50) NOT NULL,
 Descripcion VARCHAR(200) NULL);
CREATE TABLE SubCategorias (
 SubCategoriaID INT IDENTITY(1,1) PRIMARY KEY,
 CategoriaID INT NOT NULL,
 Nombre VARCHAR(50) NOT NULL,
 CONSTRAINT FK_SubCat_Cat FOREIGN KEY (CategoriaID) REFERENCES Categorias(CategoriaID));
CREATE TABLE Productos (
 ProductoID INT IDENTITY(1,1) PRIMARY KEY,
 Codigo VARCHAR(20) NOT NULL UNIQUE,
 Nombre VARCHAR(100) NOT NULL,
 SubCategoriaID INT NOT NULL,
 PrecioBase DECIMAL(10,2) NOT NULL,
 Activo BIT NOT NULL DEFAULT 1,
 CONSTRAINT FK_Prod_SubCat FOREIGN KEY (SubCategoriaID) REFERENCES SubCategorias(SubCategoriaID));





CREATE TABLE Ciudades (
 CiudadID INT IDENTITY(1,1) PRIMARY KEY,
 Nombre VARCHAR(50) NOT NULL,
 Pais VARCHAR(50) NOT NULL,
 Region VARCHAR(50) NULL);
CREATE TABLE Clientes (
 ClienteID INT IDENTITY(1,1) PRIMARY KEY,
 Documento VARCHAR(20) NOT NULL UNIQUE,
 Nombre VARCHAR(100) NOT NULL,
 Email VARCHAR(100) NULL,
 CiudadID INT NOT NULL,
 FechaAlta DATE NOT NULL,
 CONSTRAINT FK_Cliente_Ciudad FOREIGN KEY (CiudadID) REFERENCES Ciudades(CiudadID));



CREATE TABLE Vendedores (
 VendedorID INT IDENTITY(1,1) PRIMARY KEY,
 Nombre VARCHAR(100) NOT NULL,
 Sucursal VARCHAR(50) NOT NULL);

CREATE TABLE Ventas (
 VentaID INT IDENTITY(1,1) PRIMARY KEY,
 NumeroFactura VARCHAR(20) NOT NULL UNIQUE,
 Fecha DATETIME NOT NULL,
 ClienteID INT NOT NULL,
 VendedorID INT NOT NULL,
 Estado VARCHAR(20) NOT NULL DEFAULT 'Completada',
 CONSTRAINT FK_Venta_Cliente FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID),
 CONSTRAINT FK_Venta_Vendedor FOREIGN KEY (VendedorID) REFERENCES Vendedores(VendedorID));




CREATE TABLE DetalleVentas (
 DetalleID INT IDENTITY(1,1) PRIMARY KEY,
 VentaID INT NOT NULL,
 ProductoID INT NOT NULL,
 Cantidad INT NOT NULL,
 PrecioUnit DECIMAL(10,2) NOT NULL,
 Descuento DECIMAL(5,2) NOT NULL DEFAULT 0,
 CONSTRAINT FK_Det_Venta FOREIGN KEY (VentaID) REFERENCES Ventas(VentaID),
 CONSTRAINT FK_Det_Producto FOREIGN KEY (ProductoID) REFERENCES Productos(ProductoID));
Go